In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('OP_DTL_OWNRSHP_PGYR2018_P01172020.csv')
df.head()

,Change_Type,Physician_Profile_ID,Physician_First_Name,Physician_Middle_Name,Physician_Last_Name,Physician_Name_Suffix,Recipient_Primary_Business_Street_Address_Line1,Recipient_Primary_Business_Street_Address_Line2,Recipient_City,Recipient_State,...,Value_of_Interest,Terms_of_Interest,Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State,Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country,Dispute_Status_for_Publication,Interest_Held_by_Physician_or_an_Immediate_Family_Member,Payment_Publication_Date
0,CHANGED,246880,David,NaN,Siegel,NaN,92 2nd Street,NaN,Hackensack,NJ,...,0.0,Common Stock,Cornerstone Specialty Network LLC,100000216802,Cornerstone Specialty Network LLC,PA,United States,No,Physician Covered Recipient,01/17/2020
1,CHANGED,172954,James,NaN,Salwitz,NaN,3 Crommelin Court,NaN,East Brunswick,NJ,...,0.0,Common Stock,Cornerstone Specialty Network LLC,100000216802,Cornerstone Specialty Network LLC,PA,United States,No,Physician Covered Recipient,01/17/2020
2,CHANGED,997719,Jamie,NaN,Koprivnikar,NaN,39 High Street,NaN,Montclair,NJ,...,0.0,Common Stock,Cornerstone Specialty Network LLC,100000216802,Cornerstone Specialty Network LLC,PA,United States,No,Physician Covered Recipient,01/17/2020
3,CHANGED,1274562,Jeffrey,NaN,Silberberg,NaN,1 Milton Ct,NaN,Marlboro Township,NJ,...,0.0,Common Stock,Cornerstone Specialty Network LLC,100000216802,Cornerstone Specialty Network LLC,PA,United States,No,Physician Covered Recipient,01/17/2020
4,CHANGED,1013,Joel,NaN,Silver,NaN,62 Coventry Lane,NaN,Avon,CT,...,0.0,Common Stock,Cornerstone Specialty Network LLC,100000216802,Cornerstone Specialty Network LLC,PA,United States,No,Physician Covered Recipient,01/17/2020

In [3]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

# simplify the variable names
df.columns = df.columns.str.replace('physician_' , '').str.replace('recipient_', '').str.replace('submitting_applicable_manufacturer_or_applicable_gpo', 'submitting_org').str.replace('applicable_manufacturer_or_applicable_gpo_making', 'org').str.replace('_by_or_an_immediate_family_member', '').str.replace('primary_business_street_', '')
df.columns

Index(['change_type', 'profile_id', 'first_name', 'middle_name', 'last_name',
       'name_suffix', 'address_line1', 'address_line2', 'city', 'state',
       'zip_code', 'country', 'province', 'postal_code', 'primary_type',
       'specialty', 'record_id', 'program_year',
       'total_amount_invested_usdollars', 'value_of_interest',
       'terms_of_interest', 'submitting_org_name', 'org_payment_id',
       'org_payment_name', 'org_payment_state', 'org_payment_country',
       'dispute_status_for_publication', 'interest_held',
       'payment_publication_date'],
      dtype='object')

# Inconsistencies

In [4]:
df[['first_name','middle_name','last_name', 'address_line1', 'address_line2', 'city', 'state']].sample(20)

,first_name,middle_name,last_name,address_line1,address_line2,city,state
2546,Kim,W,Johnston,840 Pine Street,Ste. 880,Macon,GA
1513,Timothy,NaN,Hlavinka,7909 Fredericksburg Rd,Suites 120,San Antonio,TX
347,Gary,NaN,Reiser,90 Humphrey St,NaN,Swampscott,MA
310,John,NaN,Dorchak,1765 Central Church Rd,NaN,Midland,GA
3001,Kenneth,NaN,Adcook,1555 Saxon Blvd,Ste 401,Deltona,FL
14,Sameer,P,Desai,16 Cottonwood Drive,NaN,Windsor,NJ
2957,Christopher,NaN,Barry,1257 E 33rd St,NaN,Edmond,OK
2710,Judith,NaN,Gurdian,9711 Medical Center Drive,Suite 109,Rockville,MD
53,Sameh,NaN,Mikhail,1914 Tewksbury Road,NaN,Columbus,OH
588,DAVID,L,CUNNINGHAM,1901 SE 18TH AVE BLDG 300,NaN,OCALA,FL
1667,Arnold,NaN,Schwartz,206 East Jericho Turnpike,NaN,Huntington Station,NY
2879,Frederic,NaN,Moll,275 Shoreline Drive Suite 100,NaN,Redwood City,CA
2268,chirag,a,shah,1101 Madison St. #1500,NaN,seattle,WA
1815,SUDIP,NaN,BOSE,9229 LBJ FWY,NaN,DALLAS,TX
1098,JAY,NaN,STALLMAN,1100 JOHNSON FERRY RD NE,SUITE 593,ATLANTA,GA
1820,BIJAN,NaN,GHATAN,20401 AVALON BLVD SUITE B,NaN,CARSON,CA
29,Allan,NaN,Deutsch,345 E 80th St,NaN,New York,NY
178,Jonathan,B,Rosefsky,1164 Saint Andrews Rd,NaN,Bryn Mawr,PA
1945,Christopher,NaN,Digiovanni,100 BUTLER DR,NaN,Providence,RI
3018,Barry,K,Bartee,3234 64th St,NaN,Lubbock,TX

Seems like the name columns are not capitalized uniformly, let's change that.

In [5]:
df['first_name'] = df['first_name'].str.lower().str.capitalize()
df['middle_name'] = df['middle_name'].str.lower().str.capitalize()
df['last_name'] = df['last_name'].str.lower().str.capitalize()

# do this with address lines, city, interest_held
df['address_line1'] = df['address_line1'].str.lower().str.title()
df['address_line2'] = df['address_line2'].str.lower().str.title()
df['city'] = df['city'].str.lower().str.title()
df['interest_held'] = df['interest_held'].str.lower().str.title()

df.sample(5)

,change_type,profile_id,first_name,middle_name,last_name,name_suffix,address_line1,address_line2,city,state,...,value_of_interest,terms_of_interest,submitting_org_name,org_payment_id,org_payment_name,org_payment_state,org_payment_country,dispute_status_for_publication,interest_held,payment_publication_date
106,UNCHANGED,75853,Samuel,NaN,Stagg,NaN,Po Box 4176,NaN,Houma,LA,...,92774.00,Stock Ownership,Arthrosurface Incorporated,100000005469,Arthrosurface Incorporated,MA,United States,No,Physician Covered Recipient,01/17/2020
2717,UNCHANGED,298211,Charles,NaN,Edwards,II,301 St Paul Place,NaN,Baltimore,MD,...,5891.88,Limited Liability Company Membership Interest,"Calvary Spine, LLC",100000076381,"Calvary Spine, LLC",MD,United States,No,Physician Covered Recipient,01/17/2020
2819,UNCHANGED,245762,John,NaN,Heymach,NaN,2036 Southgate Blvd,NaN,Houston,TX,...,122.13,A 2% royalty paid to members of IGIP based on ...,"IGIP, LLC",100000316812,"IGIP, LLC",KY,United States,No,Physician Covered Recipient,01/17/2020
2450,UNCHANGED,26614,David,NaN,Wohns,NaN,2900 Bradford St Ne,NaN,Grand Rapids,MI,...,2932.00,"4,206 shares at 1.75/share Latest valuation a...","Ablative Solutions, Inc.",100000076383,"Ablative Solutions, Inc.",CA,United States,No,Physician Covered Recipient,01/17/2020
330,UNCHANGED,271394,Andrew,NaN,Goldberg,NaN,2380 Sutter Street 3Rd Floor,NaN,San Francisco,CA,...,8800.00,Common Stock options,"Siesta Medical, Inc.",100000010385,"Siesta Medical, Inc.",CA,United States,No,Physician Covered Recipient,01/17/2020

Names & addresses are correctly capitalized now!

# Name Suffix

In [6]:
df['name_suffix'].unique()

array([nan, 'Jr', 'III', 'JR', 'MD', 'Jr.', 'Sr', 'M.D.', 'D.O.', 'DO',
       'JR MD', 'IIIMD', 'II MD', 'IV', 'JR.', 'DDS', 'Mr', 'OD', 'Mrs',
       'DPM', 'II', 'DMD', 'I', 'Sr.'], dtype=object)

Alright. This can get complicated. Not only is there inconsistent capitlizations, some suffixes have dots and some don't... Let me do some research really quick.

So after some googling, here are some findings:
- 'Jr' and 'Sr' should have a period at the end when displaying in a full name. e.g. "John F. Kennedy Jr."
- MD, OD, DPM, DMD all need periods in between. e.g. 'M.D.'
- 'Mr' needs a period

In [7]:
import fuzzywuzzy
from fuzzywuzzy import process

/opt/anaconda3/lib/python3.7/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [8]:
suffixes = df['name_suffix'].unique()
suffixes

array([nan, 'Jr', 'III', 'JR', 'MD', 'Jr.', 'Sr', 'M.D.', 'D.O.', 'DO',
       'JR MD', 'IIIMD', 'II MD', 'IV', 'JR.', 'DDS', 'Mr', 'OD', 'Mrs',
       'DPM', 'II', 'DMD', 'I', 'Sr.'], dtype=object)

In [9]:
def match_strings(data, column, string_to_match, min_ratio):
    # get the list of unique strings under the column
    strings = df[column].unique()
    
    # get the top 10 closets matches for the stringt to match
    matches = fuzzywuzzy.process.extract(string_to_match, strings, limit = 10, scorer = fuzzywuzzy.fuzz.token_sort_ratio)
    
    # get the matches that satisfy the min_ratio
    close_matches = [matches[0] for matches in matches if matches[1] == min_ratio]
    
    # get the rows with those close matches
    rows_with_match = df[column].isin(close_matches)
    rows_with_match
    # replace rows with string to match
    df.loc[rows_with_match, column] = string_to_match
    
    print('Finish!')

In [10]:
# Change all jr's to 'Jr.'
match_strings(df, 'name_suffix', 'Jr.', 100)

#fuzzywuzzy.process.extract('Jr.', suffixes, limit = 10, scorer = fuzzywuzzy.fuzz.token_sort_ratio) 
match_strings(df, 'name_suffix', 'Sr.', 100)

# do this with mr and mrs as well
match_strings(df, 'name_suffix', 'Mr.', 100)

match_strings(df, 'name_suffix', 'Mrs.', 100)

Finish!
Finish!
Finish!
Finish!

In [11]:
# replace 'MD' with 'M.D.'
df.loc[df.name_suffix == 'MD', 'name_suffix'] = 'M.D.'
# replace 'JR MD' with 'Jr., M.D.'
df.loc[df.name_suffix == 'JR MD', 'name_suffix'] = 'Jr., M.D.'
# replace 'DPM' with 'D.P.M.','DMD' with 'D.M.D.' & 'DDS' with 'D.D.S.'
df.loc[df.name_suffix == 'DPM', 'name_suffix'] = 'D.P.M.'
df.loc[df.name_suffix == 'DMD', 'name_suffix'] = 'D.M.D.'
df.loc[df.name_suffix == 'DDS', 'name_suffix'] = 'D.D.S.'
df.loc[df.name_suffix == 'OD', 'name_suffix'] = 'O.D.'

# do this with the number suffixes combined with MD
df.loc[df.name_suffix == 'IIIMD', 'name_suffix'] = 'III M.D.'
df.loc[df.name_suffix == 'II MD', 'name_suffix'] = 'II M.D.'
df.loc[df.name_suffix == 'II MD', 'name_suffix'] = 'II M.D.'

In [12]:
df['name_suffix'].unique()

array([nan, 'Jr.', 'III', 'M.D.', 'Sr.', 'D.O.', 'DO', 'Jr., M.D.',
       'III M.D.', 'II M.D.', 'IV', 'D.D.S.', 'Mr.', 'O.D.', 'Mrs.',
       'D.P.M.', 'II', 'D.M.D.', 'I'], dtype=object)

Looks pretty good for now.

# Null Values

Let's look with the null values!

In [13]:
df.isnull().sum()

change_type                           0
profile_id                            0
first_name                            0
middle_name                        2355
last_name                             0
name_suffix                        2851
address_line1                         0
address_line2                      1994
city                                  0
state                                 0
zip_code                              0
country                               0
province                           3288
postal_code                        3288
primary_type                          0
specialty                           153
record_id                             0
program_year                          0
total_amount_invested_usdollars       0
value_of_interest                     0
terms_of_interest                     0
submitting_org_name                   0
org_payment_id                        0
org_payment_name                      0
org_payment_state                    12
org_payment_country                   0
dispute_status_for_publication        0
interest_held                         0
payment_publication_date              0
dtype: int64

columns with null values:
    - middle_name
        - Null value here means no middle name which is fine, replace with empty string ('')
    - name_suffix
        - null value means no suffix, replace with empty string('')
    - address_line2
        - null value means the address provided doesn't have a second line of street address, replace with empty string ('')
    - province
        - no province provided, would just have to remove column
    - postal_code
        - with a bit of Google Search, Turns out postal code and Zip Code are essentially the same thing except Postal Code is more frequently used in the UK, and Zip Code is more frequently used here. Remove column
    - specialty
        - This just means physicians don't have a specialty, replace with ('N/A')
    - org_payment_state
        - every org would need a state, might need further investigation

In [14]:
df = df.drop('province', axis = 1).drop('postal_code', axis = 1)
df.columns

Index(['change_type', 'profile_id', 'first_name', 'middle_name', 'last_name',
       'name_suffix', 'address_line1', 'address_line2', 'city', 'state',
       'zip_code', 'country', 'primary_type', 'specialty', 'record_id',
       'program_year', 'total_amount_invested_usdollars', 'value_of_interest',
       'terms_of_interest', 'submitting_org_name', 'org_payment_id',
       'org_payment_name', 'org_payment_state', 'org_payment_country',
       'dispute_status_for_publication', 'interest_held',
       'payment_publication_date'],
      dtype='object')

In [15]:
# replace middle_name with ('')
df['middle_name'] = df['middle_name'].fillna('')
# replace name_suffix with ('')
df['name_suffix'] = df['name_suffix'].fillna('')
# replace address_line2 with ('')
df['address_line2'] = df['address_line2'].fillna('')
# replace specialty with ('N/A')
df['specialty'] = df['specialty'].fillna('N/A')

In [16]:
# org_payment_state
df[df['org_payment_state'].isnull()]

,change_type,profile_id,first_name,middle_name,last_name,name_suffix,address_line1,address_line2,city,state,...,value_of_interest,terms_of_interest,submitting_org_name,org_payment_id,org_payment_name,org_payment_state,org_payment_country,dispute_status_for_publication,interest_held,payment_publication_date
301,UNCHANGED,201832,Bert,,Altmanshofer,,1798 Old Route 220 N Suite 201,,Duncansville,PA,...,12291.00,Purchased stock at market value.,Kerecis Limited,100000151666,Kerecis Limited,NaN,Iceland,No,Physician Covered Recipient,01/17/2020
2406,UNCHANGED,194086,Amin,,Kassam,,2801 W Kinnickinnic River Pkwy,Suite 630,Milwaukee,WI,...,4677360.54,COMMON SHARES,Synaptive Medical Inc.,100000136564,Synaptive Medical Inc.,NaN,Canada,No,Physician Covered Recipient,01/17/2020
2407,UNCHANGED,194086,Amin,,Kassam,,2801 W Kinnickinnic River Pkwy,Suite 630,Milwaukee,WI,...,1870944.22,COMMON SHARES,Synaptive Medical Inc.,100000136564,Synaptive Medical Inc.,NaN,Canada,No,Immediate Family Member,01/17/2020
2408,UNCHANGED,175241,Steven,,Kalkanis,,Henry Ford Health System,2799 West Grand Boulevard,Detroit,MI,...,67372.70,COMMON SHARES,Synaptive Medical Inc.,100000136564,Synaptive Medical Inc.,NaN,Canada,No,Physician Covered Recipient,01/17/2020
2409,UNCHANGED,310698,Mitesh,,Shah,,8333 Naab Rd,Suite 250,Indianapolis,IN,...,128533.87,COMMON SHARES,Synaptive Medical Inc.,100000136564,Synaptive Medical Inc.,NaN,Canada,No,Physician Covered Recipient,01/17/2020
2410,UNCHANGED,265914,Keyvan,,Abtin,,Po Box 10605,,Eugene,OR,...,85446.02,COMMON SHARES,Synaptive Medical Inc.,100000136564,Synaptive Medical Inc.,NaN,Canada,No,Physician Covered Recipient,01/17/2020
2411,UNCHANGED,1237184,Thomas,,Doers,,3003 W Good Hope Rd,,Milwaukee,WI,...,286179.63,COMMON SHARES,Synaptive Medical Inc.,100000136564,Synaptive Medical Inc.,NaN,Canada,No,Physician Covered Recipient,01/17/2020
2412,UNCHANGED,1222669,Allen,,Waziri,,Po Box 110429,,Aurora,CO,...,191397.59,COMMON SHARES,Synaptive Medical Inc.,100000136564,Synaptive Medical Inc.,NaN,Canada,No,Physician Covered Recipient,01/17/2020
2413,UNCHANGED,276974,William,,Choi,,Po Box 974737,,Dallas,TX,...,289640.87,COMMON SHARES,Synaptive Medical Inc.,100000136564,Synaptive Medical Inc.,NaN,Canada,No,Physician Covered Recipient,01/17/2020
2414,UNCHANGED,327034,Burak,,Ozgur,,361 Hospital Rd,224,Newport Beach,CA,...,9766.33,COMMON SHARES,Synaptive Medical Inc.,100000136564,Synaptive Medical Inc.,NaN,Canada,No,Physician Covered Recipient,01/17/2020
2445,UNCHANGED,310698,Mitesh,,Shah,,8333 Naab Rd,Suite 250,Indianapolis,IN,...,105806.45,DEBENTURES - 15% INTEREST RATE,Synaptive Medical Inc.,100000136564,Synaptive Medical Inc.,NaN,Canada,No,Physician Covered Recipient,01/17/2020
2624,UNCHANGED,264262,Bela,,Denes,,9648 Olive Blvd,Pmb 236,Saint Louis,MO,...,12376.98,Physician is an employee of Blue Earth Diagnos...,Blue Earth Diagnostics Limited,100000151603,Blue Earth Diagnostics Limited,NaN,Great Britain (Uk),No,Physician Covered Recipient,01/17/2020

Those without states are organizations that are not in the US. Replace those without states with ('N/A')

In [17]:
df['org_payment_state'] = df['org_payment_state'].fillna('N/A')

# Converting Date Object

Let's check the type of the date column

In [18]:
df['payment_publication_date'].dtype

dtype('O')

It's an object, would have to convert it so that it is recognize as date.

In [19]:
# convert date
df['payment_publication_date'] = pd.to_datetime(df['payment_publication_date'], format = '%m/%d/%Y')

In [20]:
df['payment_publication_date'].dtype

dtype('<M8[ns]')

Now it's converted to date, we can interact with the column a lot easier! For example:

In [21]:
# day of the payment publication
df['payment_publication_date'].dt.day.head(5)

# month of the payment publication
df['payment_publication_date'].dt.month.head(5)

0    1
1    1
2    1
3    1
4    1
Name: payment_publication_date, dtype: int64

In [22]:
df.isnull().sum()

change_type                        0
profile_id                         0
first_name                         0
middle_name                        0
last_name                          0
name_suffix                        0
address_line1                      0
address_line2                      0
city                               0
state                              0
zip_code                           0
country                            0
primary_type                       0
specialty                          0
record_id                          0
program_year                       0
total_amount_invested_usdollars    0
value_of_interest                  0
terms_of_interest                  0
submitting_org_name                0
org_payment_id                     0
org_payment_name                   0
org_payment_state                  0
org_payment_country                0
dispute_status_for_publication     0
interest_held                      0
payment_publication_date           0
dtype: int64

All null values and dates are handled!

# Save as a new CSV

In [23]:
# saving the new dataframe as a separate dataset
df.to_csv('new_ownership_data.csv')